export default {
    mon: [
        {
            title: 'Honest Candidate',
            description: 'A comedy about a third term congresswoman named Joo Sang Sook who is an expert liar, but one day can’t lie anymore, with only a day to go before the elections.',
            genres: 'Comedy',
            times: [
                '14:10',
                '18:20',
            ],
            duration: '105',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/_/b_ho_ng_n_i_d_i_cgv_1.jpg',
        },
        {
            title: 'Bloodshot',
            description: 'Based on the bestselling comic book, Vin Diesel stars as Ray Garrison, a soldier recently killed in action and brought back to life as the superhero Bloodshot by the RST corporation. With an army of nanotechnology in his veins, he\'s an unstoppable force -- stronger than ever and able to heal instantly. But in controlling his body, the company has sway over his mind and memories, too. Now, Ray doesn\'t know what\'s real and what\'s not -- but he\'s on a mission to find out.',
            genres: 'Action',
            times: [
                '20:00',
            ],
            duration: '110',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/l/bloodshot_cgv_1.jpg',
        },
        {
            title: 'Escape From Pretoria',
            description: 'Based on the real-life prison break of two political captives, Escape From Pretoria is a race-against-time thriller set in the tumultuous apartheid days of South Africa.\n',
            genres: 'Thriller',
            times: [
                '14:30',
                '19:30',
            ],
            duration: '106',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/p/r/pretoria_poster_1__1.jpg',
        },
        {
            title: 'The Dustwalker',
            description: 'One by one the residents of a small, isolated town become infected by an insidious bug that turns them into violent, indiscriminate killing machines.',
            genres: 'Drama, Thriller',
            times: [
                '16:20',
            ],
            duration: '89',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/s/a/sa_m_c_ch_t__cgv_1.jpg',
        },
        {
            title: 'Nắng 3: Lời Hứa Của Cha',
            description: 'Lời Hứa Của Cha kể về cuộc sống của 2 mẹ con lừa đảo Quế Phương ( Khả Như ) và bé Hồng Ân ( Ngân Chi). Mọi thứ trở nên đảo lộn khi 2 mẹ con vô tình lừa phải bác sĩ Tùng Sơn ( Kiều Minh Tuấn ), người có khả năng là cha mà bé Hồng Ân bấy lâu đang tìm kiếm. Hành trình chinh phục người cha bất đắc dĩ của 2 mẹ con không hề suôn sẻ khi gặp phải chướng ngại đáng gờm là Thùy Linh (Oanh Kiều), người yêu hiện tại của Sơn. Số phận nghiệt ngã còn trêu đùa và thử thách tình cha con hơn nữa khi đặt Hồng Ân vào tình huống hiểm nghèo.',
            genres: 'Comedy, Drama',
            times: [
                '15:45',
            ],
            duration: '109',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_n_ng_3_-_poster_kh_ng_logo_gia_50k-01_1.jpg',
        },
        {
            title: '8 A South African Horror Story',
            description: 'An old man, fated to collect souls for eternity, seeks atonement after trading his daughter\'s soul.',
            genres: 'Horror',
            times: [
                '16:40',
            ],
            duration: '98',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_smm_-_dau_an_-_poster_chinh__1_gia_40k-01_1.jpg',
        },
        {
            title: 'Johnny English Strikes Again',
            description: 'After a cyber-attack reveals the identity of all of the active undercover agents in Britain, Johnny English is forced to come out of retirement to find the mastermind hacker.',
            genres: 'Action, Adventure',
            times: [
                '15:40',
            ],
            duration: '89',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/2/4/240_2_1.png',
        },
        {
            title: 'Vu Quy Đại Náo',
            description: 'Trang and Hien promised with each other when they were teenagers that one will not get married if the other doesn’t. However, they are both being pressured by their family to get married. Can’t stand the pressure, Trang asks Hien, together with Hoang, the one that was arranged to marry Trang, to run away from their homes. Being a smart, business woman, Trang has an idea of starting a wedding planning business with the friends. On the way, they picked up a singer, Tai, to join the team and are lucky to meet Mrs. Hai, who gives them a shelter and supports them. An unique wedding planner team is formed with many fun adventures ahead.',
            genres: 'Comedy, Family, Romance',
            times: [
                '18:45',
            ],
            duration: '115',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/v/q/vqdn240.jpg',
        },
        {
            title: 'Danur 3',
            description: 'After years of being friendly with her little ghosts, a girl begins to feel that she must have a normal life like other girls. Especially, now she has a boyfriend, but she doesn\'t tell him about her ability to see ghosts.',
            genres: 'Horror',
            times: [
                '13:50',
                '18:00',
                '20:30',
            ],
            duration: '90',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/4/x/4x5_1__1.jpg',
        },
        {
            title: 'Dreamkatcher',
            description: 'In order to stop his bad dreams a young boy steals a dreamcatcher from a mysterious neighbor forcing his family to rescue him from a nightmarish entity.',
            genres: 'Horror, Mystery',
            times: [
                '15:10',
                '17:10',
                '19:10',
            ],
            duration: '84',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/d/r/dreamkatcher-poster_1.png',
        }
    ],
    tue: [
        {
            title: 'Honest Candidate',
            description: 'A comedy about a third term congresswoman named Joo Sang Sook who is an expert liar, but one day can’t lie anymore, with only a day to go before the elections.',
            genres: 'Comedy',
            times: [
                '14:10',
                '18:20',
            ],
            duration: '105',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/_/b_ho_ng_n_i_d_i_cgv_1.jpg',
        },
        {
            title: 'Bloodshot',
            description: 'Based on the bestselling comic book, Vin Diesel stars as Ray Garrison, a soldier recently killed in action and brought back to life as the superhero Bloodshot by the RST corporation. With an army of nanotechnology in his veins, he\'s an unstoppable force -- stronger than ever and able to heal instantly. But in controlling his body, the company has sway over his mind and memories, too. Now, Ray doesn\'t know what\'s real and what\'s not -- but he\'s on a mission to find out.',
            genres: 'Action',
            times: [
                '20:00',
            ],
            duration: '110',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/l/bloodshot_cgv_1.jpg',
        },
        {
            title: 'Escape From Pretoria',
            description: 'Based on the real-life prison break of two political captives, Escape From Pretoria is a race-against-time thriller set in the tumultuous apartheid days of South Africa.\n',
            genres: 'Thriller',
            times: [
                '14:30',
                '19:30',
            ],
            duration: '106',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/p/r/pretoria_poster_1__1.jpg',
        },
        {
            title: 'The Dustwalker',
            description: 'One by one the residents of a small, isolated town become infected by an insidious bug that turns them into violent, indiscriminate killing machines.',
            genres: 'Drama, Thriller',
            times: [
                '16:20',
            ],
            duration: '89',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/s/a/sa_m_c_ch_t__cgv_1.jpg',
        },
        {
            title: 'Nắng 3: Lời Hứa Của Cha',
            description: 'Lời Hứa Của Cha kể về cuộc sống của 2 mẹ con lừa đảo Quế Phương ( Khả Như ) và bé Hồng Ân ( Ngân Chi). Mọi thứ trở nên đảo lộn khi 2 mẹ con vô tình lừa phải bác sĩ Tùng Sơn ( Kiều Minh Tuấn ), người có khả năng là cha mà bé Hồng Ân bấy lâu đang tìm kiếm. Hành trình chinh phục người cha bất đắc dĩ của 2 mẹ con không hề suôn sẻ khi gặp phải chướng ngại đáng gờm là Thùy Linh (Oanh Kiều), người yêu hiện tại của Sơn. Số phận nghiệt ngã còn trêu đùa và thử thách tình cha con hơn nữa khi đặt Hồng Ân vào tình huống hiểm nghèo.',
            genres: 'Comedy, Drama',
            times: [
                '15:45',
            ],
            duration: '109',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_n_ng_3_-_poster_kh_ng_logo_gia_50k-01_1.jpg',
        },
        {
            title: '8 A South African Horror Story',
            description: 'An old man, fated to collect souls for eternity, seeks atonement after trading his daughter\'s soul.',
            genres: 'Horror',
            times: [
                '16:40',
            ],
            duration: '98',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_smm_-_dau_an_-_poster_chinh__1_gia_40k-01_1.jpg',
        },
        {
            title: 'Johnny English Strikes Again',
            description: 'After a cyber-attack reveals the identity of all of the active undercover agents in Britain, Johnny English is forced to come out of retirement to find the mastermind hacker.',
            genres: 'Action, Adventure',
            times: [
                '15:40',
            ],
            duration: '89',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/2/4/240_2_1.png',
        },
        {
            title: 'Vu Quy Đại Náo',
            description: 'Trang and Hien promised with each other when they were teenagers that one will not get married if the other doesn’t. However, they are both being pressured by their family to get married. Can’t stand the pressure, Trang asks Hien, together with Hoang, the one that was arranged to marry Trang, to run away from their homes. Being a smart, business woman, Trang has an idea of starting a wedding planning business with the friends. On the way, they picked up a singer, Tai, to join the team and are lucky to meet Mrs. Hai, who gives them a shelter and supports them. An unique wedding planner team is formed with many fun adventures ahead.',
            genres: 'Comedy, Family, Romance',
            times: [
                '18:45',
            ],
            duration: '115',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/v/q/vqdn240.jpg',
        },
        {
            title: 'Danur 3',
            description: 'After years of being friendly with her little ghosts, a girl begins to feel that she must have a normal life like other girls. Especially, now she has a boyfriend, but she doesn\'t tell him about her ability to see ghosts.',
            genres: 'Horror',
            times: [
                '13:50',
                '18:00',
                '20:30',
            ],
            duration: '90',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/4/x/4x5_1__1.jpg',
        },
        {
            title: 'Dreamkatcher',
            description: 'In order to stop his bad dreams a young boy steals a dreamcatcher from a mysterious neighbor forcing his family to rescue him from a nightmarish entity.',
            genres: 'Horror, Mystery',
            times: [
                '15:10',
                '17:10',
                '19:10',
            ],
            duration: '84',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/d/r/dreamkatcher-poster_1.png',
        }
    ],
    wed: [
        {
            title: 'Honest Candidate',
            description: 'A comedy about a third term congresswoman named Joo Sang Sook who is an expert liar, but one day can’t lie anymore, with only a day to go before the elections.',
            genres: 'Comedy',
            times: [
                '14:10',
                '18:20',
            ],
            duration: '105',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/_/b_ho_ng_n_i_d_i_cgv_1.jpg',
        },
        {
            title: 'Bloodshot',
            description: 'Based on the bestselling comic book, Vin Diesel stars as Ray Garrison, a soldier recently killed in action and brought back to life as the superhero Bloodshot by the RST corporation. With an army of nanotechnology in his veins, he\'s an unstoppable force -- stronger than ever and able to heal instantly. But in controlling his body, the company has sway over his mind and memories, too. Now, Ray doesn\'t know what\'s real and what\'s not -- but he\'s on a mission to find out.',
            genres: 'Action',
            times: [
                '20:00',
            ],
            duration: '110',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/l/bloodshot_cgv_1.jpg',
        },
        {
            title: 'Escape From Pretoria',
            description: 'Based on the real-life prison break of two political captives, Escape From Pretoria is a race-against-time thriller set in the tumultuous apartheid days of South Africa.\n',
            genres: 'Thriller',
            times: [
                '14:30',
                '19:30',
            ],
            duration: '106',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/p/r/pretoria_poster_1__1.jpg',
        },
        {
            title: 'The Dustwalker',
            description: 'One by one the residents of a small, isolated town become infected by an insidious bug that turns them into violent, indiscriminate killing machines.',
            genres: 'Drama, Thriller',
            times: [
                '16:20',
            ],
            duration: '89',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/s/a/sa_m_c_ch_t__cgv_1.jpg',
        },
        {
            title: 'Nắng 3: Lời Hứa Của Cha',
            description: 'Lời Hứa Của Cha kể về cuộc sống của 2 mẹ con lừa đảo Quế Phương ( Khả Như ) và bé Hồng Ân ( Ngân Chi). Mọi thứ trở nên đảo lộn khi 2 mẹ con vô tình lừa phải bác sĩ Tùng Sơn ( Kiều Minh Tuấn ), người có khả năng là cha mà bé Hồng Ân bấy lâu đang tìm kiếm. Hành trình chinh phục người cha bất đắc dĩ của 2 mẹ con không hề suôn sẻ khi gặp phải chướng ngại đáng gờm là Thùy Linh (Oanh Kiều), người yêu hiện tại của Sơn. Số phận nghiệt ngã còn trêu đùa và thử thách tình cha con hơn nữa khi đặt Hồng Ân vào tình huống hiểm nghèo.',
            genres: 'Comedy, Drama',
            times: [
                '15:45',
            ],
            duration: '109',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_n_ng_3_-_poster_kh_ng_logo_gia_50k-01_1.jpg',
        },
        {
            title: '8 A South African Horror Story',
            description: 'An old man, fated to collect souls for eternity, seeks atonement after trading his daughter\'s soul.',
            genres: 'Horror',
            times: [
                '16:40',
            ],
            duration: '98',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_smm_-_dau_an_-_poster_chinh__1_gia_40k-01_1.jpg',
        },
        {
            title: 'Johnny English Strikes Again',
            description: 'After a cyber-attack reveals the identity of all of the active undercover agents in Britain, Johnny English is forced to come out of retirement to find the mastermind hacker.',
            genres: 'Action, Adventure',
            times: [
                '15:40',
            ],
            duration: '89',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/2/4/240_2_1.png',
        },
        {
            title: 'Vu Quy Đại Náo',
            description: 'Trang and Hien promised with each other when they were teenagers that one will not get married if the other doesn’t. However, they are both being pressured by their family to get married. Can’t stand the pressure, Trang asks Hien, together with Hoang, the one that was arranged to marry Trang, to run away from their homes. Being a smart, business woman, Trang has an idea of starting a wedding planning business with the friends. On the way, they picked up a singer, Tai, to join the team and are lucky to meet Mrs. Hai, who gives them a shelter and supports them. An unique wedding planner team is formed with many fun adventures ahead.',
            genres: 'Comedy, Family, Romance',
            times: [
                '18:45',
            ],
            duration: '115',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/v/q/vqdn240.jpg',
        },
        {
            title: 'Danur 3',
            description: 'After years of being friendly with her little ghosts, a girl begins to feel that she must have a normal life like other girls. Especially, now she has a boyfriend, but she doesn\'t tell him about her ability to see ghosts.',
            genres: 'Horror',
            times: [
                '13:50',
                '18:00',
                '20:30',
            ],
            duration: '90',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/4/x/4x5_1__1.jpg',
        },
        {
            title: 'Dreamkatcher',
            description: 'In order to stop his bad dreams a young boy steals a dreamcatcher from a mysterious neighbor forcing his family to rescue him from a nightmarish entity.',
            genres: 'Horror, Mystery',
            times: [
                '15:10',
                '17:10',
                '19:10',
            ],
            duration: '84',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/d/r/dreamkatcher-poster_1.png',
        }
    ],
    thu: [
        {
            title: 'Honest Candidate',
            description: 'A comedy about a third term congresswoman named Joo Sang Sook who is an expert liar, but one day can’t lie anymore, with only a day to go before the elections.',
            genres: 'Comedy',
            times: [
                '14:10',
                '18:20',
            ],
            duration: '105',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/_/b_ho_ng_n_i_d_i_cgv_1.jpg',
        },
        {
            title: 'Bloodshot',
            description: 'Based on the bestselling comic book, Vin Diesel stars as Ray Garrison, a soldier recently killed in action and brought back to life as the superhero Bloodshot by the RST corporation. With an army of nanotechnology in his veins, he\'s an unstoppable force -- stronger than ever and able to heal instantly. But in controlling his body, the company has sway over his mind and memories, too. Now, Ray doesn\'t know what\'s real and what\'s not -- but he\'s on a mission to find out.',
            genres: 'Action',
            times: [
                '20:00',
            ],
            duration: '110',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/l/bloodshot_cgv_1.jpg',
        },
        {
            title: 'Escape From Pretoria',
            description: 'Based on the real-life prison break of two political captives, Escape From Pretoria is a race-against-time thriller set in the tumultuous apartheid days of South Africa.\n',
            genres: 'Thriller',
            times: [
                '14:30',
                '19:30',
            ],
            duration: '106',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/p/r/pretoria_poster_1__1.jpg',
        },
        {
            title: 'The Dustwalker',
            description: 'One by one the residents of a small, isolated town become infected by an insidious bug that turns them into violent, indiscriminate killing machines.',
            genres: 'Drama, Thriller',
            times: [
                '16:20',
            ],
            duration: '89',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/s/a/sa_m_c_ch_t__cgv_1.jpg',
        },
        {
            title: 'Nắng 3: Lời Hứa Của Cha',
            description: 'Lời Hứa Của Cha kể về cuộc sống của 2 mẹ con lừa đảo Quế Phương ( Khả Như ) và bé Hồng Ân ( Ngân Chi). Mọi thứ trở nên đảo lộn khi 2 mẹ con vô tình lừa phải bác sĩ Tùng Sơn ( Kiều Minh Tuấn ), người có khả năng là cha mà bé Hồng Ân bấy lâu đang tìm kiếm. Hành trình chinh phục người cha bất đắc dĩ của 2 mẹ con không hề suôn sẻ khi gặp phải chướng ngại đáng gờm là Thùy Linh (Oanh Kiều), người yêu hiện tại của Sơn. Số phận nghiệt ngã còn trêu đùa và thử thách tình cha con hơn nữa khi đặt Hồng Ân vào tình huống hiểm nghèo.',
            genres: 'Comedy, Drama',
            times: [
                '15:45',
            ],
            duration: '109',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_n_ng_3_-_poster_kh_ng_logo_gia_50k-01_1.jpg',
        },
        {
            title: '8 A South African Horror Story',
            description: 'An old man, fated to collect souls for eternity, seeks atonement after trading his daughter\'s soul.',
            genres: 'Horror',
            times: [
                '16:40',
            ],
            duration: '98',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_smm_-_dau_an_-_poster_chinh__1_gia_40k-01_1.jpg',
        },
        {
            title: 'Johnny English Strikes Again',
            description: 'After a cyber-attack reveals the identity of all of the active undercover agents in Britain, Johnny English is forced to come out of retirement to find the mastermind hacker.',
            genres: 'Action, Adventure',
            times: [
                '15:40',
            ],
            duration: '89',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/2/4/240_2_1.png',
        },
        {
            title: 'Vu Quy Đại Náo',
            description: 'Trang and Hien promised with each other when they were teenagers that one will not get married if the other doesn’t. However, they are both being pressured by their family to get married. Can’t stand the pressure, Trang asks Hien, together with Hoang, the one that was arranged to marry Trang, to run away from their homes. Being a smart, business woman, Trang has an idea of starting a wedding planning business with the friends. On the way, they picked up a singer, Tai, to join the team and are lucky to meet Mrs. Hai, who gives them a shelter and supports them. An unique wedding planner team is formed with many fun adventures ahead.',
            genres: 'Comedy, Family, Romance',
            times: [
                '18:45',
            ],
            duration: '115',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/v/q/vqdn240.jpg',
        },
        {
            title: 'Danur 3',
            description: 'After years of being friendly with her little ghosts, a girl begins to feel that she must have a normal life like other girls. Especially, now she has a boyfriend, but she doesn\'t tell him about her ability to see ghosts.',
            genres: 'Horror',
            times: [
                '13:50',
                '18:00',
                '20:30',
            ],
            duration: '90',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/4/x/4x5_1__1.jpg',
        },
        {
            title: 'Dreamkatcher',
            description: 'In order to stop his bad dreams a young boy steals a dreamcatcher from a mysterious neighbor forcing his family to rescue him from a nightmarish entity.',
            genres: 'Horror, Mystery',
            times: [
                '15:10',
                '17:10',
                '19:10',
            ],
            duration: '84',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/d/r/dreamkatcher-poster_1.png',
        }
    ],
    fri: [
        {
            title: 'Honest Candidate',
            description: 'A comedy about a third term congresswoman named Joo Sang Sook who is an expert liar, but one day can’t lie anymore, with only a day to go before the elections.',
            genres: 'Comedy',
            times: [
                '14:00',
                '18:10',
            ],
            duration: '105',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/_/b_ho_ng_n_i_d_i_cgv_1.jpg',
        },
        {
            title: 'Bloodshot',
            description: 'Based on the bestselling comic book, Vin Diesel stars as Ray Garrison, a soldier recently killed in action and brought back to life as the superhero Bloodshot by the RST corporation. With an army of nanotechnology in his veins, he\'s an unstoppable force -- stronger than ever and able to heal instantly. But in controlling his body, the company has sway over his mind and memories, too. Now, Ray doesn\'t know what\'s real and what\'s not -- but he\'s on a mission to find out.',
            genres: 'Action',
            times: [
                '20:00',
            ],
            duration: '110',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/l/bloodshot_cgv_1.jpg',
        },
        {
            title: 'Escape From Pretoria',
            description: 'Based on the real-life prison break of two political captives, Escape From Pretoria is a race-against-time thriller set in the tumultuous apartheid days of South Africa.\n',
            genres: 'Thriller',
            times: [
                '14:15',
                '19:30',
            ],
            duration: '106',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/p/r/pretoria_poster_1__1.jpg',
        },
        {
            title: 'The Dustwalker',
            description: 'One by one the residents of a small, isolated town become infected by an insidious bug that turns them into violent, indiscriminate killing machines.',
            genres: 'Drama, Thriller',
            times: [
                '16:10',
            ],
            duration: '89',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/s/a/sa_m_c_ch_t__cgv_1.jpg',
        },
        {
            title: 'Nắng 3: Lời Hứa Của Cha',
            description: 'Lời Hứa Của Cha kể về cuộc sống của 2 mẹ con lừa đảo Quế Phương ( Khả Như ) và bé Hồng Ân ( Ngân Chi). Mọi thứ trở nên đảo lộn khi 2 mẹ con vô tình lừa phải bác sĩ Tùng Sơn ( Kiều Minh Tuấn ), người có khả năng là cha mà bé Hồng Ân bấy lâu đang tìm kiếm. Hành trình chinh phục người cha bất đắc dĩ của 2 mẹ con không hề suôn sẻ khi gặp phải chướng ngại đáng gờm là Thùy Linh (Oanh Kiều), người yêu hiện tại của Sơn. Số phận nghiệt ngã còn trêu đùa và thử thách tình cha con hơn nữa khi đặt Hồng Ân vào tình huống hiểm nghèo.',
            genres: 'Comedy, Drama',
            times: [
                '15:45',
            ],
            duration: '109',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_n_ng_3_-_poster_kh_ng_logo_gia_50k-01_1.jpg',
        },
        {
            title: '8 A South African Horror Story',
            description: 'An old man, fated to collect souls for eternity, seeks atonement after trading his daughter\'s soul.',
            genres: 'Horror',
            times: [
                '16:30',
            ],
            duration: '98',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_smm_-_dau_an_-_poster_chinh__1_gia_40k-01_1.jpg',
        },
        {
            title: 'Johnny English Strikes Again',
            description: 'After a cyber-attack reveals the identity of all of the active undercover agents in Britain, Johnny English is forced to come out of retirement to find the mastermind hacker.',
            genres: 'Action, Adventure',
            times: [
                '15:50',
            ],
            duration: '89',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/2/4/240_2_1.png',
        },
        {
            title: 'Vu Quy Đại Náo',
            description: 'Trang and Hien promised with each other when they were teenagers that one will not get married if the other doesn’t. However, they are both being pressured by their family to get married. Can’t stand the pressure, Trang asks Hien, together with Hoang, the one that was arranged to marry Trang, to run away from their homes. Being a smart, business woman, Trang has an idea of starting a wedding planning business with the friends. On the way, they picked up a singer, Tai, to join the team and are lucky to meet Mrs. Hai, who gives them a shelter and supports them. An unique wedding planner team is formed with many fun adventures ahead.',
            genres: 'Comedy, Family, Romance',
            times: [
                '18:40',
            ],
            duration: '115',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/v/q/vqdn240.jpg',
        },
        {
            title: 'Danur 3',
            description: 'After years of being friendly with her little ghosts, a girl begins to feel that she must have a normal life like other girls. Especially, now she has a boyfriend, but she doesn\'t tell him about her ability to see ghosts.',
            genres: 'Horror',
            times: [
                '13:50',
                '18:00',
                '20:20',
            ],
            duration: '90',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/4/x/4x5_1__1.jpg',
        },
        {
            title: 'Dreamkatcher',
            description: 'In order to stop his bad dreams a young boy steals a dreamcatcher from a mysterious neighbor forcing his family to rescue him from a nightmarish entity.',
            genres: 'Horror, Mystery',
            times: [
                '15:10',
                '17:10',
                '19:10',
            ],
            duration: '84',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/d/r/dreamkatcher-poster_1.png',
        }
    ],
    sat: [
        {
            title: 'Honest Candidate',
            description: 'A comedy about a third term congresswoman named Joo Sang Sook who is an expert liar, but one day can’t lie anymore, with only a day to go before the elections.',
            genres: 'Comedy',
            times: [
                '14:10',
                '18:20',
            ],
            duration: '105',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/_/b_ho_ng_n_i_d_i_cgv_1.jpg',
        },
        {
            title: 'Bloodshot',
            description: 'Based on the bestselling comic book, Vin Diesel stars as Ray Garrison, a soldier recently killed in action and brought back to life as the superhero Bloodshot by the RST corporation. With an army of nanotechnology in his veins, he\'s an unstoppable force -- stronger than ever and able to heal instantly. But in controlling his body, the company has sway over his mind and memories, too. Now, Ray doesn\'t know what\'s real and what\'s not -- but he\'s on a mission to find out.',
            genres: 'Action',
            times: [
                '20:00',
            ],
            duration: '110',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/l/bloodshot_cgv_1.jpg',
        },
        {
            title: 'Escape From Pretoria',
            description: 'Based on the real-life prison break of two political captives, Escape From Pretoria is a race-against-time thriller set in the tumultuous apartheid days of South Africa.\n',
            genres: 'Thriller',
            times: [
                '14:35',
                '19:30',
            ],
            duration: '106',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/p/r/pretoria_poster_1__1.jpg',
        },
        {
            title: 'The Dustwalker',
            description: 'One by one the residents of a small, isolated town become infected by an insidious bug that turns them into violent, indiscriminate killing machines.',
            genres: 'Drama, Thriller',
            times: [
                '16:20',
            ],
            duration: '89',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/s/a/sa_m_c_ch_t__cgv_1.jpg',
        },
        {
            title: 'Nắng 3: Lời Hứa Của Cha',
            description: 'Lời Hứa Của Cha kể về cuộc sống của 2 mẹ con lừa đảo Quế Phương ( Khả Như ) và bé Hồng Ân ( Ngân Chi). Mọi thứ trở nên đảo lộn khi 2 mẹ con vô tình lừa phải bác sĩ Tùng Sơn ( Kiều Minh Tuấn ), người có khả năng là cha mà bé Hồng Ân bấy lâu đang tìm kiếm. Hành trình chinh phục người cha bất đắc dĩ của 2 mẹ con không hề suôn sẻ khi gặp phải chướng ngại đáng gờm là Thùy Linh (Oanh Kiều), người yêu hiện tại của Sơn. Số phận nghiệt ngã còn trêu đùa và thử thách tình cha con hơn nữa khi đặt Hồng Ân vào tình huống hiểm nghèo.',
            genres: 'Comedy, Drama',
            times: [
                '15:45',
            ],
            duration: '109',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_n_ng_3_-_poster_kh_ng_logo_gia_50k-01_1.jpg',
        },
        {
            title: '8 A South African Horror Story',
            description: 'An old man, fated to collect souls for eternity, seeks atonement after trading his daughter\'s soul.',
            genres: 'Horror',
            times: [
                '16:40',
            ],
            duration: '98',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_smm_-_dau_an_-_poster_chinh__1_gia_40k-01_1.jpg',
        },
        {
            title: 'Johnny English Strikes Again',
            description: 'After a cyber-attack reveals the identity of all of the active undercover agents in Britain, Johnny English is forced to come out of retirement to find the mastermind hacker.',
            genres: 'Action, Adventure',
            times: [
                '15:40',
            ],
            duration: '89',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/2/4/240_2_1.png',
        },
        {
            title: 'Vu Quy Đại Náo',
            description: 'Trang and Hien promised with each other when they were teenagers that one will not get married if the other doesn’t. However, they are both being pressured by their family to get married. Can’t stand the pressure, Trang asks Hien, together with Hoang, the one that was arranged to marry Trang, to run away from their homes. Being a smart, business woman, Trang has an idea of starting a wedding planning business with the friends. On the way, they picked up a singer, Tai, to join the team and are lucky to meet Mrs. Hai, who gives them a shelter and supports them. An unique wedding planner team is formed with many fun adventures ahead.',
            genres: 'Comedy, Family, Romance',
            times: [
                '18:45',
            ],
            duration: '115',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/v/q/vqdn240.jpg',
        },
        {
            title: 'Danur 3',
            description: 'After years of being friendly with her little ghosts, a girl begins to feel that she must have a normal life like other girls. Especially, now she has a boyfriend, but she doesn\'t tell him about her ability to see ghosts.',
            genres: 'Horror',
            times: [
                '13:50',
                '18:00',
                '20:30',
            ],
            duration: '90',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/4/x/4x5_1__1.jpg',
        },
        {
            title: 'Dreamkatcher',
            description: 'In order to stop his bad dreams a young boy steals a dreamcatcher from a mysterious neighbor forcing his family to rescue him from a nightmarish entity.',
            genres: 'Horror, Mystery',
            times: [
                '15:10',
                '17:10',
                '19:10',
            ],
            duration: '84',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/d/r/dreamkatcher-poster_1.png',
        }
    ],
    sun: [
        {
            title: 'Honest Candidate',
            description: 'A comedy about a third term congresswoman named Joo Sang Sook who is an expert liar, but one day can’t lie anymore, with only a day to go before the elections.',
            genres: 'Comedy',
            times: [
                '14:10',
                '18:20',
            ],
            duration: '105',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/_/b_ho_ng_n_i_d_i_cgv_1.jpg',
        },
        {
            title: 'Bloodshot',
            description: 'Based on the bestselling comic book, Vin Diesel stars as Ray Garrison, a soldier recently killed in action and brought back to life as the superhero Bloodshot by the RST corporation. With an army of nanotechnology in his veins, he\'s an unstoppable force -- stronger than ever and able to heal instantly. But in controlling his body, the company has sway over his mind and memories, too. Now, Ray doesn\'t know what\'s real and what\'s not -- but he\'s on a mission to find out.',
            genres: 'Action',
            times: [
                '20:00',
            ],
            duration: '110',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/b/l/bloodshot_cgv_1.jpg',
        },
        {
            title: 'Escape From Pretoria',
            description: 'Based on the real-life prison break of two political captives, Escape From Pretoria is a race-against-time thriller set in the tumultuous apartheid days of South Africa.\n',
            genres: 'Thriller',
            times: [
                '14:30',
                '19:30',
            ],
            duration: '106',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/p/r/pretoria_poster_1__1.jpg',
        },
        {
            title: 'The Dustwalker',
            description: 'One by one the residents of a small, isolated town become infected by an insidious bug that turns them into violent, indiscriminate killing machines.',
            genres: 'Drama, Thriller',
            times: [
                '16:20',
            ],
            duration: '89',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/s/a/sa_m_c_ch_t__cgv_1.jpg',
        },
        {
            title: 'Nắng 3: Lời Hứa Của Cha',
            description: 'Lời Hứa Của Cha kể về cuộc sống của 2 mẹ con lừa đảo Quế Phương ( Khả Như ) và bé Hồng Ân ( Ngân Chi). Mọi thứ trở nên đảo lộn khi 2 mẹ con vô tình lừa phải bác sĩ Tùng Sơn ( Kiều Minh Tuấn ), người có khả năng là cha mà bé Hồng Ân bấy lâu đang tìm kiếm. Hành trình chinh phục người cha bất đắc dĩ của 2 mẹ con không hề suôn sẻ khi gặp phải chướng ngại đáng gờm là Thùy Linh (Oanh Kiều), người yêu hiện tại của Sơn. Số phận nghiệt ngã còn trêu đùa và thử thách tình cha con hơn nữa khi đặt Hồng Ân vào tình huống hiểm nghèo.',
            genres: 'Comedy, Drama',
            times: [
                '15:45',
            ],
            duration: '109',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_n_ng_3_-_poster_kh_ng_logo_gia_50k-01_1.jpg',
        },
        {
            title: '8 A South African Horror Story',
            description: 'An old man, fated to collect souls for eternity, seeks atonement after trading his daughter\'s soul.',
            genres: 'Horror',
            times: [
                '16:40',
            ],
            duration: '98',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/r/s/rsz_smm_-_dau_an_-_poster_chinh__1_gia_40k-01_1.jpg',
        },
        {
            title: 'Johnny English Strikes Again',
            description: 'After a cyber-attack reveals the identity of all of the active undercover agents in Britain, Johnny English is forced to come out of retirement to find the mastermind hacker.',
            genres: 'Action, Adventure',
            times: [
                '15:40',
            ],
            duration: '89',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/2/4/240_2_1.png',
        },
        {
            title: 'Vu Quy Đại Náo',
            description: 'Trang and Hien promised with each other when they were teenagers that one will not get married if the other doesn’t. However, they are both being pressured by their family to get married. Can’t stand the pressure, Trang asks Hien, together with Hoang, the one that was arranged to marry Trang, to run away from their homes. Being a smart, business woman, Trang has an idea of starting a wedding planning business with the friends. On the way, they picked up a singer, Tai, to join the team and are lucky to meet Mrs. Hai, who gives them a shelter and supports them. An unique wedding planner team is formed with many fun adventures ahead.',
            genres: 'Comedy, Family, Romance',
            times: [
                '18:45',
            ],
            duration: '115',
            certificate: '13',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/v/q/vqdn240.jpg',
        },
        {
            title: 'Danur 3',
            description: 'After years of being friendly with her little ghosts, a girl begins to feel that she must have a normal life like other girls. Especially, now she has a boyfriend, but she doesn\'t tell him about her ability to see ghosts.',
            genres: 'Horror',
            times: [
                '13:50',
                '18:00',
                '20:30',
            ],
            duration: '90',
            certificate: '16',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/4/x/4x5_1__1.jpg',
        },
        {
            title: 'Dreamkatcher',
            description: 'In order to stop his bad dreams a young boy steals a dreamcatcher from a mysterious neighbor forcing his family to rescue him from a nightmarish entity.',
            genres: 'Horror, Mystery',
            times: [
                '15:10',
                '17:10',
                '19:10',
            ],
            duration: '84',
            certificate: '18',
            imageUrl: 'https://www.cgv.vn/media/catalog/product/cache/3/small_image/185x260/a134659ca47b28f7b266e1777fbf870f/d/r/dreamkatcher-poster_1.png',
        }
    ]
};
